apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-demo
    tcpdump-sidecar: "true"
  name: test-demo
spec:
  shareProcessNamespace: true
  containers:
    - name: nginx
      image: nginx
      stdin: true
      tty: true
      volumeMounts:
          - mountPath: /etc/nginx/data
            name: nginx-persistent-storage
  volumes:
    - name: nginx-persistent-storage
      persistentVolumeClaim:
        claimName: nginx-persistent-volume-claim