---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-tcpdump-webhook
 # namespace: webhook-demo
  namespace: default
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCekNDQXUrZ0F3SUJBZ0lVTzRBSW05Z0dtc0xRUG04Nkt0SUVFUEpyWmJvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakE1Ck1EQTBNakF3V2hjTk5ESXdOakEwTURBME1qQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMbVJmWmorClloSklWWFd1eFJjaGV4ZmdnUFpEQVhUTGJzMTZHb3BCeWdvWVRpODltdlRFa3pjZ0F5ZVRVdGI1YXFua1VacFcKNm9ydjRuMitOTDI3VGpGZnhmclVrSElOOU1pYXBoVDlyY3lnQThtK3JsQmdqOFlZRHdpYWMycTc0ZXdXL0NYegp3WVNydHAwcG82WWNJOTZnMVAxZ1dqY0w3TUo3cjY0THVrS2gzb2QxbmorZ1B5bm5OVk9BWXpDOUVwL0F0UUtECkdyTXI3dXhqcmhEV1loRzdVcUZNVVJpdm5lM1ZiVDV6S2JyaTAwWnhCdVA3cEp5aU9QS2FJK0RaQWNJQUMxRFQKZTVoNklWbkVXZC82RFdOeVpxeitpZ1BrUnZwQ1VSbnNobmpXOEpXQnJjcytRRk9RMm5PQ1ZOVjJHUTdIeXFScwozbnB2SFlhZEJEMjRFSmtDQXdFQUFhT0IxRENCMFRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZFL0sKZzJRSU1jVU1WaHlicE0zVW94akMxUlo4TUhNR0ExVWRFUVJzTUdxQ0QzUmpjR1IxYlhBdGQyVmlhRzl2YTRJcApkR053WkhWdGNDMTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0czUmpjR1IxCmJYQXRkMlZpYUc5dmF5NWtaV1poZFd4MExuTjJZNElKYkc5allXeG9iM04waHdSL0FBQUJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDQVd1aTZkbFFXQkUwb0FrV1VnM2Y2OUgvN2U0R2orKzEyL1Zjak9NNUx2ZUFOSHNucApIRVZxNzI3RmVkTU83MlRZR0xtTVVURkVqaXZuZ3lMNkVWbUVRRUpLOVc2ZEhwNjY4dXVxdENPcTMyb3JSM2FhCk9rYW11MmtkOFBNa1hGMVg2amQ2bWtyY1Y3aHR1Y0FXeGZkZXdERXgxd0FiWmF1SHdaVE1MUXBzcHlGM0s3T1QKRzJrNFJicGpPQlN0ZjNLQnIxZGp1Q1RsdWJHazk4T0Y4K2drbXJtNlllUmFUelpOYzFDSzZGV3RDckFaa1ZpZwowZUFSbWl0UXdUZFdzTDlST2x3SVdadjlwRTBSY21VbzhqNE16Y212MnJZQTFSK0s3aFI2NGhrbGpLd3hYRWJCCmhWREthbWMyNDd2OVQ4SHlmN1dmWmo3UisyVDR5djlyU2NmNgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdVpGOW1QNWlFa2hWZGE3RkZ5RjdGK0NBOWtNQmRNdHV6WG9haWtIS0NoaE9MejJhCjlNU1ROeUFESjVOUzF2bHFxZVJSbWxicWl1L2lmYjQwdmJ0T01WL0YrdFNRY2czMHlKcW1GUDJ0ektBRHliNnUKVUdDUHhoZ1BDSnB6YXJ2aDdCYjhKZlBCaEt1Mm5TbWpwaHdqM3FEVS9XQmFOd3Zzd251dnJndTZRcUhlaDNXZQpQNkEvS2VjMVU0QmpNTDBTbjhDMUFvTWFzeXZ1N0dPdUVOWmlFYnRTb1V4UkdLK2Q3ZFZ0UG5NcHV1TFRSbkVHCjQvdWtuS0k0OHBvajROa0J3Z0FMVU5ON21Ib2hXY1JaMy9vTlkzSm1yUDZLQStSRytrSlJHZXlHZU5id2xZR3QKeXo1QVU1RGFjNEpVMVhZWkRzZktwR3plZW04ZGhwMEVQYmdRbVFJREFRQUJBb0lCQVFDZzhoQVdCdVAyYVdnOQpwblJvaUhCam1DTWg4NkdxczlxSk9wTVVRTlZFQmlxaGpIUCtRUlJSNW1EMkRTLzNKZUllTWRtWTNET1doMUpRCnJ3eTlWbHdPTkx2WXZrMzlyaDhWY2hRRDlyV3IyVWtQekdNUmNYNmhXREtKeXJPNTZmU2J1SisvSnZnNzRsYUQKWHg4QnJqeHFGZUpGVkRGS3R2d0UvaE8wQjVYbnZWVFlkT3FsaDl5UXJITmd4OFdhOFo0ak9wWE1sdG9NdzlkawpVdmxSQ1ZORnVnYVE0NUxMSHZiRmY2ZDNMRm5sQzA4cTMzVU9ieG1hd3VsTTJOdHNma0MwOGk5eWFPZDk1YnFKCklXZkw4TFFUUXJqTi9QVmI0cUlpYUdnZmhmZWk1dGo2TVdUV042bm8vcDRFYjBGQm5oWWkwK0Y1L3RqNGxGWUIKa1FHeURFNkJBb0dCQU5uSmcwWndpVGpqU0NDTUhqb2hGYjhYZjByV2NLRnYwaTdseTJtd2cweFA3UXgySFNrKwp2ZnBUMkM5Q2pwSXZaNFdoWWwyQlg3ZzRWTlkzOHVoYTJqQ2llaXllamxHUUtlVEVHRm93NTZFY0dIY3YvVU9ZCmVzZXE0b1lNajE3aXB4dGhyUmc2YTJxb3ZlVnoyV0Y5dzlkbTJ1UEVkU1pNbHB2MHJyUmVFWHJSQW9HQkFOb2cKeUk1dHpSOFNRcUNLR1lSYXNkMWp0V0RUZFFiN0toQXhSN05NMHlLcEFheXZNdDVENlFLaVNhMFd1UXlNREZlcQpOUENRU0FTQmQyMmpiUzZTelJYS29zNFVSbzFDeWliL3BYYk92ckE3YWFUNWNQalhySnphMEVwOTVsTnRXbkdZCnI4ZDB1Z2IxVS9Eb3MvSVpuNTd5cUIrQ3R4Y1hEaDhDYjRDSVNCdEpBb0dBT1l5OGVkS25FRGRQQ2ZxOHloT1EKRVl6K0FDS21aS0tONGdLck8rUis3WjE1UUgrOXVQWnhjVUxTcjdwZ3ZsUjBnS1ZpdnQ2L0Vva2dNZk5hNXZlTApES3NDcWVQRUs5MXlsSmNVOEZCWUJRVE5ta0UrSmF5WFZVZmMwQnRsajJkSlRUMEVacENaYmZmbEprcjB1SVJwClNmUk9CejRVenVnU0xHZjkrbitaRXVFQ2dZQjhCRG1pNlFDL2tyVTQ2MnVZbWF3WXNGRDJiU05UUmNmamp2RXkKR3hMTDJRVXZ0aWlZd0VtaGlyMlM0S0Z6WmNpNnF2WVFkQ2ZPRUFIajN3LzdjOUdRZXpaWExxWHlPTEFRdmpiSQpOc0dxRncxNGs2M01mV3NSZjBML3AxY2x4YjJ2YWwwK2JMbzdySTMrSVgvMXZPWEpERFBVUHBCMFcxSlhCUjU2CkdJSE9xUUtCZ0RRV1pTZlRGdWViRXNKWGdEMXN4SXQzUjdmVjFPckwwZkJ1bDAwS3hJdFBTT2E0bFRQeHZSeUMKd3BpV21Tc1cwT05lQU15b1ZqdUxPUVR5Q3VFdVFsMDYzUW8rSE5BcFY0K1dXVHBlbXljN3o2NWpDclYrR3hYcwp2VENxVE1uc1RlRkV6U002NFFlVElrYlNRYk90QmdKRnZiTit3RXBwQ0k4bldiTFljRTNwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-webhook
  #namespace: webhook-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tcpdump-webhook
  template:
    metadata:
      labels:
        component: tcpdump-webhook
    spec:
      containers:
        - name: tcpdump-ws
          image: dyslexicat/tcpdump-webhook:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8443
          volumeMounts:
            - name: ssl-tcpdump-webhook
              mountPath: /ssl
      volumes:
        - name: ssl-tcpdump-webhook
          configMap:
            name: ssl-tcpdump-webhook
---

kind: Service
apiVersion: v1
metadata:
  #namespace: webhook-demo
  namespace: default
  name: tcpdump-webhook
spec:
  selector:
    component: tcpdump-webhook
  ports:
    - name: http
      port: 443
      targetPort: 8443