---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-tcpdump-webhook
 # namespace: webhook-demo
  namespace: default
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCekNDQXUrZ0F3SUJBZ0lVZStZeEtWc0hRNFVNYndRYUdURjh5NDBvQzRrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakU0Ck1qTXpNVEF3V2hjTk5ESXdOakV6TWpNek1UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOcTNMY3Z2CjJlK25GdjdnbENuNFB4SmV3MUxuRHA0dDhteFBDb1U5dENNL3dYK2dvOWhMbVlrRTBuTWhzZGRGR0lqNUJlQlAKMjdaMFFhU2xRUzIyUDQ4NThYa241VVByRFBtNXVLdHVWODQwMVRHdjlOZ0ZmbUg3Tm02VGlwVzJKTE9IL1ZMeQplYXVYNFBxMm5YVU5aeTBYNXptVVFtWDdaVWwvYzRxd2N3K1QyRWJWcEwraWdxazZlM0t6WmMzWFJDam9SOHV4ClV2TUhWNU84S1RraUcyZXlIOUFGY2dMR2JjclFWQU41ZzhrVTFTZFhLWFVQR084ODdHR1Y1a25EeGhHWS92bHYKZ1dpSVY2ZUZkZVZFZVBtcHZJV3E1WmxaS0JqR0xNcm5jVnVZVjcybXl5MnNrL01KRkhrcEdjVXRYVzFXNWFUSQo2NzFXWlVIS2ZhclAyNjhDQXdFQUFhT0IxRENCMFRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZQZkkKc0JpUWtDUTJkSnBSRFJDaWpXVlpuVXFtTUhNR0ExVWRFUVJzTUdxQ0QzUmpjR1IxYlhBdGQyVmlhRzl2YTRJcApkR053WkhWdGNDMTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0czUmpjR1IxCmJYQXRkMlZpYUc5dmF5NWtaV1poZFd4MExuTjJZNElKYkc5allXeG9iM04waHdSL0FBQUJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCWXBTUllJWUZwUHN4a2ZzOTZITGVEZ0h6N2lqeERQOGlqWUhoRjlxSHJYNXNFck5tNQpTUzdaN0FYNXhqQXdKYW5HbFIyK2ZSV0ZRWGZTaXo1UlkvRnJkaURERnU0T0VYeUtoUjgzem5TeWdoZTk4K3EyCjJRdzRCRFZ0OTE0MHZibS83NnM5TkFMeEpXSjZvOGpzQ2txdkZKQ2l6T2FZN0tOdVk5Y1hEOG5rR1BUTXpOdkYKSk5tdzFkZWM1Z1hSa0RNc1RvZG91MnZ0dUttbll2a0huaENZa0FlWElud01KY1hPL1Vhdmc2dTlKNXZzd3E0awpuUm00ZVl2UnExMlFhTmxpaFlzczZjVUF3YUJKQ3F1K3MxR2VMcFRlUUpLTmFXaVdsS1VPem9XUmY1OU5RQ2tkCnNUcGw1d1V6QkhLenRaQUpkWHFZNXJWbHhTSHNaU1FMQ1FaeAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMnJjdHkrL1o3NmNXL3VDVUtmZy9FbDdEVXVjT25pM3liRThLaFQyMEl6L0JmNkNqCjJFdVppUVRTY3lHeDEwVVlpUGtGNEUvYnRuUkJwS1ZCTGJZL2p6bnhlU2ZsUStzTStibTRxMjVYempUVk1hLzAKMkFWK1lmczJicE9LbGJZa3M0ZjlVdko1cTVmZytyYWRkUTFuTFJmbk9aUkNaZnRsU1g5emlyQnpENVBZUnRXawp2NktDcVRwN2NyTmx6ZGRFS09oSHk3RlM4d2RYazd3cE9TSWJaN0lmMEFWeUFzWnR5dEJVQTNtRHlSVFZKMWNwCmRROFk3enpzWVpYbVNjUEdFWmorK1crQmFJaFhwNFYxNVVSNCthbThoYXJsbVZrb0dNWXN5dWR4VzVoWHZhYkwKTGF5VDh3a1VlU2taeFMxZGJWYmxwTWpydlZabFFjcDlxcy9icndJREFRQUJBb0lCQVFESTd6c3F2Z3M1cWdkdApWNE9uWDBNS3JIYkVCalNleTlXSS9jRExrbG1aZkt4WGhZeWhYU3NMLzVzY1hOdFd5MHIwSTl2ckxWTE1OOWhLCjIrdWFoSEcyTXVTT2kwR00rVGZ0Z1Z1UVc0cGRqcHBDME1XZlpNU3NYYSt2UE9zNENhT0VNSzVoOHhRbXVoemUKR01GbDFVOXgxU0QvL0I1WU5QTGo2Q3lOUVBna1dOdGczK2UreDdmWVdsQXNFVGxVeTVTKzJNN1NybnFtVjE5SQpESHFTOHRGSjRXZCtTTmRKclZ6YlUrK2IzRG1TL3hzRkIySmdGaDlxVUs5S3ZaQ3JJQ2EwSUVKNGE0Rll6TjBoCnNGb1VUdFlrNkhvVnVmY3F5dmlRYjFOdTZGTUVhamR0aFBnREpubkoyMmhiUyttTndIdnNYVGtIbm8vbkFvOGgKTkdPa0ovQ3hBb0dCQVBYNUpFSVIvTDUva2tDVm1XUitOaXFhSWdoS1QvUzBJckliclB1aGU1MzZSc25DbnpFQgpXVmU4NzhUYWZzU1A4L2xWYjd3Q29obTVyM0lVWm1yeFBXSXE5RjZWbGF0SGpINVo4RTU4Z2Nta3hzMU5ldVRWClVscWExSG1jUEMrZzlJcVFxR0gzVDQ0anRDdkE4SjZ2SFp5dHJ0enVpaFJOdzkxcVRKcFBDVGdKQW9HQkFPT2gKbHQ1RnlSUmJUMFUzSDl1MUlsektYYmFkWStuaHMyeWFWYU1mNTFhWG5iS2lNaXFQNCtvdEpvVC92dVZmeGx1Ygo0TkthNmdEcnUwTnQ4MjFIR08xTFU4SUlOd3Z2VGVBOVgxeEdKR2x3ejF6NTNSUlp6bDNGMFdkRXg1ZG95VS9mCjZ6QzUxMmlMaWd3LzEwZWViM2F0ZnY5bzFXczNGSXdyMFEwQytUUDNBb0dCQUxERHAzdlhvMU5mS0VKRGYrV0oKRWZJUnJDMWJBaFN2czFOZHNqVnUrZ0F3a05pRGhaVlpDOVNTa1poZEVNYS9VS3c0NnNBcEFFY09ldmUzazFaOQpJUWpBSjdjbE5sYk5aemlSOTdEZnB3RzY2YWMyYS8reEVhck5JNjUxU1lkTTJ4QU5Id1N3RHJydUM1ZDU0ekdXClZPaDRwSFplOGxuZS9NZk1rVm8vUERmSkFvR0FLc0tWQzZZQ1V0K2dNWGxjYzdKQUJUeENoR1ptZVczYmZhQTAKVEJOWEtxNEtncDd6VzRseUgvQmhWd1NQd0pqUU15OUIrVzMrWFRQckZveVYrTVl0U1k0bjZzQU9UeUNoK1dpdAovREIwOEpXdmJtREZoZWdrMnZxcERvUWVGalFwOU9ZMFVRL29CZ3lJWHlxeTd4STFFQThoVnl0RFJBT3h5VzhGCnN6TUd5eHNDZ1lFQWxHSWQyL05yMWtCeGxsUWRJV0FyWHJvMVpoM1FkYWhLc3RGaWFXSUdwd3l0cE5zdGRGMlcKNHNFcVVZVVdzcUtVVWNweG9ZSHVIRTRUU3h4RmFBR1pJK1p6RkRaS0lUVXJwWkt4alJDQjA0bG5Gd1I1MUZuWAo3bW94aWZBMVZrYVB1V3Q1a0pSYzYwQkRNUWRxWXdPMEJ3RlA3ME9qK3lOMFNVL2hiNWMrT01FPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-webhook
  #namespace: webhook-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tcpdump-webhook
  template:
    metadata:
      labels:
        component: tcpdump-webhook
    spec:
      containers:
        - name: tcpdump-ws
          image: dyslexicat/tcpdump-webhook:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8443
          volumeMounts:
            - name: ssl-tcpdump-webhook
              mountPath: /ssl
      volumes:
        - name: ssl-tcpdump-webhook
          configMap:
            name: ssl-tcpdump-webhook
---

kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: tcpdump-webhook
spec:
  selector:
    component: tcpdump-webhook
  ports:
    - name: http
      port: 443
      targetPort: 8443