apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tcpdump-webhook
webhooks:
  - name: tcpdump-webhook.default.svc.cluster.local
    failurePolicy: Fail
    clientConfig:
      service:
        name: tcpdump-webhook
       # namespace: webhook-demo
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVRFE5OGdPNk9iUytTRm5uN2JzUFF1dkRtTlJNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakU0Ck1qTXpNVEF3V2hjTk1qY3dOakUzTWpNek1UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOWEIzeHV2CmthSXNZdU80SGxpVzcyMXJZcHAwd3VBanFGTEJFY1FMWG50UFZ5elRsS0VyU0lVbkYyWG0wSHh0ZlJ0RDdHcWEKMm5YNE9Pd0ZxSDNzYmRCSjdZSWZiOEhuMTBPbTMwaHVOMnZkL29nSVp0TEIrTDFCRmVVWDVJYzRIUU41QlAxYgpGNlREWHlHMXhjRjlzWlM0ajZObWl6RVZrdHZFWU85TyttNm5zNWIybkM2QnRYUWxzWmhOVmR4dWphNXFBUk0wCkNEK3hYd0FCSnUreGxrWjFsSTRXQzJ4LzA3WUtiM3F3bWdyNkVFWnpacDNHR0s0V1dhd3FpRGNSaVBkVmpvWG4KUXdYVElIMkV2dlNPTzEvbERiVzZrZjdsY3J3VjEyOU9heFJpelZqbEZ1S2REVCsydG5HVlBvL0dDenRrK3FwWgprU2J6NXFQTkZFRXhmOThDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRk43RnNYcmNLczAyWUh3NnY4dytkSEwydmJOY01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUFHcEE2YTJoSzk5RUlhSlpJQ0RvZW5mZGVYUG9BSmMxVTk5MVFGNXpWOUU5TERJNkhZSzJHaApHdjljUXROZFhaMW5mWDU2aWc5UEE2bUU5a3pCZFE3M1J2OHMyMzZuOHNNNmQzYWpWVS9JeS9YSXVBU2hrdjZnCjVqZUg5aGcxNnVkQ0t2QlZDRzl4UW1wVThSMGh0QUxYZFhVeEY1dGE2SXhnR0o3dUNuZlNsSWNxa3B2STRWUHMKYmlVRHdZSnE5MHRlOXAyU2ROOUY4citkYlNYa0VRbTZSTmRBTmtUNHVEOTM4V2ZhRHZQWWx2QjRNNjVKbFVrUwpGSGErb2h6UkVtSUU4WjRWM2VMeis1dlRYUDlUN2hRK2dGNHQ0YWdFcnpqVStKWWJaeGE5SSsyWGdxVFdsM0hICnpPeUFFcHFvRDBSazRzcmxmVHhZYW1pY0JzZGs4elhmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5